# config.yaml
# Baseline Configuration for BESSTIE
# CLI precedence: CLI flags > this config file

common:
  device: auto          # auto | cuda | cpu

train:
  model_name: roberta-large
  task: Sarcasm          # Sarcasm | Sentiment
  train_file: ./dataset/train-translated.csv
  valid_file: ./dataset/valid-translated.csv
  output_dir: ./model_output

  # Grid search over learning rates (best one is saved)
  learning_rates: [2.0e-5]  #learning_rates: [1.0e-5]
  batch_size: 16
  eval_batch_size: null      # null => use batch_size
  num_epochs: 30             # Increased because Early Stopping will handle the stop
  weight_decay: 0.01
  seed: 42
  use_class_weights: False            ###############################################
  
  # ---- Early Stopping Settings ----
  early_stopping: true
  patience: 10  
  min_delta: 0.001
  monitor: f1_macro          # f1_macro | accuracy


  # ---- تنظیمات جدید برای جلوگیری از Overfit ----
  warmup_ratio: 0.1       # ۱۰٪ قدم‌ها برای گرم شدن
  hidden_dropout: 0.2     # دراپ‌آوت لایه‌های مخفی (برای دیتای کم ۰.۳ بگذارید)
  attention_dropout: 0.2  # دراپ‌آوت لایه‌های توجه
  freeze_encoder: false   # اگر خیلی اوضاع خراب بود، true کنید

  num_workers: 2
  pin_memory: true
  grad_accum_steps: 1
  max_length: 256

  # Optimization
  fp16: True              ###############################################
  bf16: False              ###############################################
  tf32: True                 ###############################################

predict:
  checkpoint_dir: ./model_output
  input_file: null          # set a CSV path to batch predict
  output_file: null         # optional
  text: []                  # list of strings for single prediction mode

  device: auto
  batch_size: 32
  max_length: 256
  fp16: false              ###############################################
  bf16: false              ###############################################