# config.yaml
# Baseline Configuration for BESSTIE
# CLI precedence: CLI flags > this config file

common:
  device: auto          # auto | cuda | cpu

train:
  model_name: roberta-large
  task: Sarcasm          # Sarcasm | Sentiment
  train_file: ./dataset/train-nottranslated.csv
  valid_file: ./dataset/train-nottranslated.csv
  output_dir: ./model_output

  # Grid search over learning rates (best one is saved)
  learning_rates: [1.0e-5, 2.0e-5, 3.0e-5]
  #learning_rates: [1.0e-5]
  batch_size: 8
  eval_batch_size: null      # null => use batch_size
  num_epochs: 30             # Increased because Early Stopping will handle the stop
  weight_decay: 0.01
  seed: 42
  use_class_weights: False            ###############################################
  
  # ---- Early Stopping Settings ----
  early_stopping: true
  patience: 5
  min_delta: 0.001
  monitor: f1_macro          # f1_macro | accuracy

  num_workers: 2
  pin_memory: true
  grad_accum_steps: 1
  max_length: 256

  # Optimization
  fp16: false               ###############################################
  bf16: false               ###############################################
  tf32: false               ###############################################

predict:
  checkpoint_dir: ./model_output
  input_file: null          # set a CSV path to batch predict
  output_file: null         # optional
  text: []                  # list of strings for single prediction mode

  device: auto
  batch_size: 32
  max_length: 256
  fp16: false              ###############################################
  bf16: false              ###############################################